hi
hello
I got this exception: I ran into a problem!
this runs whether or not an exception occurs